#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""ECG Conversion Tool

Usage:
    dicom-ecg-plot <inputfile> [--layout=LAYOUT] [--paper=PAPER] [--output=FILE|--format=FMT] [--minor-grid] [--interpretation]
    dicom-ecg-plot <stu> <ser> <obj> [--layout=LAYOUT] [--paper=PAPER] [--output=FILE|--format=FMT] [--minor-grid] [--interpretation]
    dicom-ecg-plot --help

Options:
    -h, --help                 This help.
    <inputfile>                Input dicom file.
    <stu> <ser> <obj>          studyUID seriesUID objectUID
                               UIDs for WADO download.
    -l LAYOUT --layout=LAYOUT  Layout [default: 3x4_1].
    -p PAPER --paper=PAPER     Paper format: a4, letter [default: a4].
    -o FILE --output=FILE      Output file (format deduced by extension).
    -f FMT --format=FMT        Output format.
    --minor-grid               Draw minor axis grid (1mm).
    --interpretation           Show "Automated ECG interpretation"

Valid layouts are: 3x4_1, 3x4, 12x1

The output format is deduced from the extension of the filename, if present, or
from --format option when filename is not specified.

Valid formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz,
               tif, tiff.
"""
from ecg import ECG, ECGReadFileError
from docopt import docopt
import sys


def convert(source, layout, outformat, outputfile,
            minor_axis=False, interpretation=False, paper='a4'):

    ecg = ECG(source, paper=paper)
    ecg.draw(layout, 10, minor_axis, interpretation=interpretation)
    return ecg.save(outformat=outformat, outputfile=outputfile)


if __name__ == '__main__':

    arguments = docopt(__doc__)
    inputfile = arguments['<inputfile>']
    stu = arguments['<stu>']
    ser = arguments['<ser>']
    obj = arguments['<obj>']
    outputfile = arguments['--output']
    outformat = arguments['--format']
    layout = arguments['--layout']
    minor_axis = arguments['--minor-grid']
    interpretation = arguments['--interpretation']
    paper = arguments['--paper']

    if inputfile:
        source = inputfile
    else:
        source = {'stu': stu, 'ser': ser, 'obj': obj}

    try:
        output = convert(source, layout, outformat, outputfile,
                         minor_axis, interpretation, paper)
    except (ECGReadFileError, ValueError) as e:
        sys.exit(f"Error: {e}")

    if output:
        sys.stdout.buffer.write(output)
